server:
  port: 8999   # server.port=80
  servlet:
    context-path: /probono  # server.servlet.context-path=/probono

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
#    url: jdbc:mysql://127.0.0.1:8887/fisa?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://127.0.0.1:3306/fisa?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:        # jsp 사용을 위한 필수 설정, WEB-INF 폴더 직접 만들고, pom.xml에 설정, ProbonoController의 메소드 setViewName()확인하기
    view:
      prefix: /WEB-INF/
      suffix: .jsp




#spring:
#  profiles:
#    active: live
#    
#---    
#spring:
#  config:
#    activate:
#      on-profile: live
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      
#  oracle-datasource:
#    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    jdbcUrl: jdbc:log4jdbc:oracle:thin:@localhost:1521:TEST
#    username: root
#    password: root
#
#  mysql-datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:log4jdbc:mysql://localhost:3306/TEST
#    username: system
#    password: oracle